ojsite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('openjuice.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

openjuice/urls.py
from django.urls import path

from . import views

app_name = "openjuice"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('domains/', views.domains, name='domains'),
    path('d/', views.domains, name='domains'),
    path('d/<str:code>', views.domain, name='domain'),
    # path('domain/<str:code>', views.domain, name='domain'),
    # path('topics/', views.topics, name='topics'),
    path('t/', views.topics, name='topics'),
    path('t/<str:code>', views.topic, name='topic'),
    # path('topic/<str:code>', views.topic, name='topic'),
    path('search_topics', views.search_topics, name='search_topics'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

openjuice/models.py
from django.db import models
from django.utils import timezone
import datetime


class Topic(models.Model):
    name = models.CharField(max_length=200, unique=True)
    code = models.CharField(max_length=100, unique=True)
    overview = models.TextField(max_length=500, null=False, blank=False)
    # Educational resources: Books, Videos, Lectures, Tutorials
    # Milestone projects
    # Tools (editors, IDEs, environment setup)
    # Discussions


class Domain(models.Model):
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=100, unique=True)
    topics = models.ManyToManyField(Topic)


class BookResource(models.Model):
    topics = models.ManyToManyField(Topic)
    source = models.URLField()
    title = models.CharField(max_length=200, unique=False)
    author = models.CharField(max_length=200, unique=False)
    year = models.IntegerField(unique=False, null=True, blank=True)

    class Meta:
        unique_together = ('title', 'author',)


class CourseResource(models.Model):
    topics = models.ManyToManyField(Topic)
    source = models.URLField()
    title = models.CharField(max_length=200, unique=False)
    organization = models.CharField(max_length=200, unique=False)
    year = models.IntegerField(unique=False)

    class Meta:
        unique_together = ('title', 'organization',)


class Tool(models.Model):
    topics = models.ManyToManyField(Topic)
    source = models.URLField()
    name = models.CharField(max_length=200, unique=False)
    type = models.CharField(max_length=200, unique=False)
    description = models.TextField(max_length=500, null=False, blank=False)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date < timezone.now()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

openjuice/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice, Domain, Topic


class IndexView(generic.ListView):
    template_name = 'openjuice/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'openjuice/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'openjuice/results.html'


def domains(request):
    ds = get_list_or_404(Domain)
    return render(request, 'openjuice/domains.html', {
        'domain_list': ds
    })


def domain(request, code):
    d = get_object_or_404(Domain, code=str(code).lower())
    return render(request, 'openjuice/domain.html', {
        'domain': d
    })


def topics(request):
    ts = get_list_or_404(Topic)
    return render(request, 'openjuice/topics.html', {
        'topic_list': ts
    })


def topic(request, code):
    topic = get_object_or_404(Topic, code=str(code).lower())
    return render(request, 'openjuice/topic.html', {
        'topic': topic
    })


def search_topics(request):
    try:
        topic = request.GET.get('topic', '')
        topics = Topic.objects.filter(name__icontains=topic)
    except Topic.DoesNotExist:
        raise Http404("Topic does not exist")
    return render(request, 'openjuice/topic_search_results.html', {
        'topics': topics,
        'not_found_message': 'No topics were found that match the search criteria'
    })


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'openjuice/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('openjuice:results', args=(question.id,)))

openjuice/templates/openjuice/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<ul>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'openjuice:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</ul>
</body>
</html>

openjuice/templates/openjuice/domain.html
<!DOCTYPE html>
<html lang="en">
{% extends "./navigation_bar.html" %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Domain: {{ domain.name }}</title>
<link rel="stylesheet" type="text/css" href="{% static 'openjuice/css/style.css' %}">
</head>

<body>



<ul>
<h1>{{ domain.name }}</h1>
    {% for topic in domain.topics.all %}
        <li><a href="{% url 'openjuice:topic' topic.code %}">{{ topic.name }}</a></li>
    {% endfor %}
</ul>

</body>
{% endblock %}
</html>

openjuice/templates/openjuice/domains.html
<!DOCTYPE html>
<html lang="en">
{% extends "./navigation_bar.html" %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Domains</title>
    <link rel="stylesheet" type="text/css" href="{% static 'openjuice/css/style.css' %}">
</head>
<body>


<div class="container">
    {% if domain_list %}
    <h2>Domains</h2>
    <ul>
        {% for domain in domain_list %}
        <li><a href="{% url 'openjuice:domain' domain.code %}">{{ domain.name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No domains are available.</p>
    {% endif %}
</div>
{% endblock %}

</body>
</html>

openjuice/templates/openjuice/index.html
<!DOCTYPE html>
<html lang="en">
{% extends "./navigation_bar.html" %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'openjuice/css/style.css' %}">
</head>
<body>



<div class="container">
    <h1>Welcome home!</h1>

    <p>OpenJuice is a place where users of varying levels of experience come to learn about
        various topics in Computer Science and IT.<br><br>

        We want to help you learn as much as you can using free
        material, resources and development tools.<br> OpenJuice is a community-run platform, where anybody can
        link resources and useful tools.
    </p>
</div>
{% endblock %}
</body>
</html>

openjuice/templates/openjuice/navigation_bar.html
<!doctype html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'navigation-bar.css' %}"/>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'openjuice:index' %}">OpenJuice</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'openjuice:domains' %}">Domains</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'openjuice:topics' %}">All Topics</a>
            </li>

            <!--Search textbox-->
            <li>
                <form action="{% url 'openjuice:search_topics' %}">
                <div class="md-form active-cyan-2 mb-3">
                    <input class="form-control" type="text" placeholder="Search Topics"  aria-label="Search" name="topic", value="">
                </div>
                </form>
            </li>

        </ul>

    </div>
</nav>
{% block content %}
replace this
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

openjuice/templates/openjuice/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'openjuice:detail' question.id %}">Vote again?</a>
</body>
</html>

openjuice/templates/openjuice/topic.html
<!DOCTYPE html>
<html lang="en">
{% extends "./navigation_bar.html" %}
{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'openjuice/css/style.css' %}">
    <title>Topic: {{ topic.name }}</title>
</head>

<body>
<div class="container">
    <h1>{{ topic.name }}</h1>

    <h4>Overview</h4>
    <p>{{ topic.overview }}</p>

    <h4>Educational Resources</h4>
    {% if topic.bookresource_set.all %} <h5>Books</h5> {% endif %}
    <ul>
      {% for book_rsrc in topic.bookresource_set.all %}
        <li><A target="_blank" href="{{ book_rsrc.source }}">{{ book_rsrc.title }}</A></li>
      {% endfor %}
    </ul>

    {% if topic.courseresource_set.all %} <h5>Courses</h5> {% endif %}
    <ul>
      {% for course_rsrc in topic.courseresource_set.all %}
      <li><A target="_blank" href="{{ course_rsrc.source }}">{{ course_rsrc.title }}</A> - {{ course_rsrc.organization }}
      </li>
      {% endfor %}
    </ul>

    {% if topic.tool_set.all %} <h4>Tools, Platforms and Environments</h4> {% endif %}

    <ul>
      {% for tool in topic.tool_set.all %}
      <li><A target="_blank" href="{{ tool.source }}">{{ tool.name }}</A> - {{ tool.description }}</li>
      {% endfor %}
    </ul>

    <h4>Milestone Projects</h4>
    <p>Projects go here...</p>

    <h4>Discussions</h4>
    <p>Discussions go here...</p>
</div>
</body>
{% endblock %}
</html>

openjuice/templates/openjuice/topic_search_results.html
<!DOCTYPE html>
<html lang="en">

{% extends "./navigation_bar.html" %}
{% block content %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Search results</title>
    <link rel="stylesheet" type="text/css" href="{% static 'openjuice/css/style.css' %}">
</head>
<body>

<div class="container">
    <h3>Search results</h3>

    {% if not topics %}<p><strong>{{ not_found_message }}</strong></p>{% endif %}

    {% for topic in topics %}
    <li><a href="{% url 'openjuice:topic' topic.code %}">{{ topic.name }}</a></li>
    {% endfor %}
</div>
</body>
{% endblock %}
</html>

openjuice/templates/openjuice/topics.html
<!DOCTYPE html>
<html lang="en">
{% extends "./navigation_bar.html" %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>All Topics</title>
    <link rel="stylesheet" type="text/css" href="{% static 'openjuice/css/style.css' %}">
</head>
<body>


{% if topic_list %}
    <ul>
    {% for topic in topic_list %}
        <li><a href="{% url 'openjuice:topic' topic.code %}">{{ topic.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No topics are available.</p>
{% endif %}

{% endblock %}
</body>
</html>